In [2]:
# 8. Self-Attention Mechanism
# ---------------------------------
# Example 8: Self-Attention Mechanism
# ---------------------------------

import torch
import torch.nn.functional as F

# 1. Create a random input tensor (batch_size=1, seq_len=3, embedding_dim=4)
x = torch.rand(1, 3, 4)

# 2. Define Q, K, V as the input itself (self-attention)
Q, K, V = x, x, x

# 3. Compute attention scores
d_k = x.size(-1)  # dimension of embedding
scores = torch.matmul(Q, K.transpose(-2, -1)) / (d_k ** 0.5)

# 4. Apply softmax to get attention weights
weights = F.softmax(scores, dim=-1)

# 5. Compute output as weighted sum of V
output = torch.matmul(weights, V)

# 6. Display results
print("--- Input Tensor ---")
print(x)
print("\n--- Attention Weights ---")
print(weights)
print("\n--- Self-Attention Output ---")
print(output)


--- Input Tensor ---
tensor([[[0.3997, 0.5350, 0.5081, 0.8639],
         [0.5867, 0.8990, 0.3706, 0.3396],
         [0.9523, 0.6483, 0.6517, 0.9419]]])

--- Attention Weights ---
tensor([[[0.3209, 0.2828, 0.3963],
         [0.2943, 0.3266, 0.3790],
         [0.2953, 0.2714, 0.4333]]])

--- Self-Attention Output ---
tensor([[[0.6716, 0.6828, 0.5261, 0.7466],
         [0.6702, 0.6968, 0.5176, 0.7222],
         [0.6899, 0.6828, 0.5330, 0.7554]]])
